### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by Vault108** [Vault108/PInfo#1]
- [ ] Main Rewrite
- [ ] GUI Rewrite
- [ ] Code clean up
- [ ] Add about window
- [x] Merge Hinfo And Dinfo
